services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: tacdent-sqlserver
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Tacdent_dev_2026"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - tacdent_mssql_data:/var/opt/mssql

volumes:
  tacdent_mssql_data:
